[versions]
dokka = "1.8.10"
jacoco = "0.8.9"
konf = "1.1.2"
kotlin = "1.8.20"
kotest = "5.5.5"
mockito = "5.3.0"

[libraries]
jacoco = { module = "org.jacoco:org.jacoco.core", version.ref = "jacoco" }
kotest-junit5-jvm = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
kotest-assertions-core-jvm = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
konf-yaml = { module = "com.uchuhimo:konf-yaml", version.ref = "konf" }
kotlin-gradle-plugin-api = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[bundles]
kotlin-testing = [ "kotest-junit5-jvm", "kotest-assertions-core-jvm", "mockito-core" ]

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gitSemVer = { id = "org.danilopianini.git-sensitive-semantic-versioning", version = "1.1.6" }
gradlePluginPublish = { id = "com.gradle.plugin-publish", version = "1.2.0" }
jacoco-testkit = "pl.droidsonroids.jacoco.testkit:1.0.9"
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-qa = { id = "org.danilopianini.gradle-kotlin-qa", version = "0.29.2" }
publishOnCentral = { id = "org.danilopianini.publish-on-central", version = "4.0.1" }
multiJvmTesting = { id = "org.danilopianini.multi-jvm-test-plugin", version = "0.4.20" }
taskTree = { id = "com.dorongold.task-tree", version = "2.1.1" }
