[versions]
dokka = "1.9.20"
jacoco = "0.8.12"
konf = "1.1.2"
kotlin = "2.0.10"
kotest = "5.9.1"
mockito = "5.12.0"

[libraries]
jacoco = { module = "org.jacoco:org.jacoco.core", version.ref = "jacoco" }
konf-yaml = { module = "com.uchuhimo:konf-yaml", version.ref = "konf" }
kotest-junit5-jvm = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
kotest-assertions-core-jvm = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
kotlin-gradle-plugin-api = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
ksoup = "com.mohamedrejeb.ksoup:ksoup-html:0.4.0"
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }

[bundles]
kotlin-testing = [ "kotest-junit5-jvm", "kotest-assertions-core-jvm", "mockito-core" ]

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gitSemVer = { id = "org.danilopianini.git-sensitive-semantic-versioning", version = "3.1.7" }
gradlePluginPublish = { id = "com.gradle.plugin-publish", version = "1.2.1" }
jacoco-testkit = "pl.droidsonroids.jacoco.testkit:1.0.12"
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-qa = { id = "org.danilopianini.gradle-kotlin-qa", version = "0.65.2" }
publishOnCentral = { id = "org.danilopianini.publish-on-central", version = "5.1.5" }
multiJvmTesting = { id = "org.danilopianini.multi-jvm-test-plugin", version = "1.2.4" }
taskTree = { id = "com.dorongold.task-tree", version = "4.0.0" }
